stages:
  - stage: build_frontend
    displayName: Build & Test Frontend
    dependsOn: build_python
    jobs:
      - job: frontend_ci
        displayName: Frontend CI (Lint, Typecheck, Test)
        timeoutInMinutes: 10
        pool:
          vmImage: ubuntu-latest

        steps:
          - checkout: none
          - download: current
            artifact: working

          - task: NodeTool@0
            displayName: 'Use Node 22.x'
            inputs:
              versionSpec: 22.x

          # --- Cache PNPM store and node_modules ---
          - task: Cache@2
            inputs:
              key: 'pnpm | "$(Agent.OS)" | $(Pipeline.Workspace)/working/assemblyline-ui-frontend/pnpm-lock.yaml'
              restoreKeys: |
                pnpm | "$(Agent.OS)"
              path: |
                ~/.pnpm-store
                $(Pipeline.Workspace)/working/assemblyline-ui-frontend/node_modules
            displayName: Cache PNPM dependencies

          - script: |
              npm install -g pnpm@10.8.1
              pnpm config set store-dir ~/.pnpm-store
              pnpm install --frozen-lockfile
            workingDirectory: $(Pipeline.Workspace)/working/assemblyline-ui-frontend
            displayName: Install Dependencies

          # --- Type Check + Lint + Tests (can run in parallel if needed) ---
          - script: |
              echo "--- Running TypeScript Check ---"
              pnpm run typecheck
            workingDirectory: $(Pipeline.Workspace)/working/assemblyline-ui-frontend
            displayName: TypeScript Typecheck

          - script: |
              echo "--- Running Vitest Unit Tests ---"
              pnpm run test:ci
            workingDirectory: $(Pipeline.Workspace)/working/assemblyline-ui-frontend
            displayName: Run Tests

          - script: |
              echo "--- Running ESLint ---"
              pnpm run lint:ci
            workingDirectory: $(Pipeline.Workspace)/working/assemblyline-ui-frontend
            displayName: ESLint

      - job: build_frontend
        dependsOn: frontend_ci
        displayName: Build Frontend Docker Image
        pool:
          vmImage: ubuntu-latest
        steps:
          - checkout: none
          - download: current
            artifact: working

          - task: NodeTool@0
            displayName: 'Use Node 22.x'
            inputs:
              versionSpec: 22.x

          - task: Cache@2
            inputs:
              key: 'pnpm | "$(Agent.OS)" | $(Pipeline.Workspace)/working/assemblyline-ui-frontend/pnpm-lock.yaml'
              path: ~/.pnpm-store
            displayName: Restore PNPM Cache (Build)

          - script: |
              npm install -g pnpm@10.8.1
              pnpm config set store-dir ~/.pnpm-store
              pnpm install --frozen-lockfile
              pnpm run build
            workingDirectory: $(Pipeline.Workspace)/working/assemblyline-ui-frontend
            displayName: Build Frontend Assets

          - task: Docker@2
            displayName: Login to docker registry
            inputs:
              command: login
              containerRegistry: cccstemp

          - script: |
              set -exv
              if [[ "$TAG" == *stable* ]]; then BUILD_TYPE=stable; else BUILD_TYPE=latest; fi
              VERSION=${TAG/stable}
              VERSION=${VERSION/beta/b}
              SERIES="$(expr $TAG : '\([0-9]\+\.[0-9]\+\.\)' )${BUILD_TYPE}"
              IMAGE=cccstemp.azurecr.io/assemblyline-ui-frontend

              docker build \
                --build-arg version=$VERSION \
                -t $IMAGE:$TAG \
                -t $IMAGE:$BUILD_TYPE \
                -t $IMAGE:$SERIES \
                .
              docker push $IMAGE --all-tags
            workingDirectory: $(Pipeline.Workspace)/working/assemblyline-ui-frontend
            displayName: Build & Push Docker Image
