stages:
  - stage: build_test_mcp
    displayName: Build & Test MCP
    dependsOn: [build_ui]
    jobs:
      - job: build_test_mcp
        timeoutInMinutes: 10
        services:
          elasticsearch: elasticsearch
          redis: redis
          minio: minio
        displayName: Build & Test MCP Image
        steps:
          - checkout: none
          - download: current
            artifact: working
          - task: Docker@2
            displayName: Login to docker registry
            inputs:
              command: login
              containerRegistry: cccstemp
          - script: |
              set -e

              # Build MCP image
              export IMAGE=cccstemp.azurecr.io/assemblyline-mcp
              docker build --build-arg base=$BASE \
                            --build-arg version=$VERSION \
                            --build-arg branch=$BUILD_TYPE \
                            -t $IMAGE:$TAG -t $IMAGE:$BUILD_TYPE -t $IMAGE:$SERIES \
                            .

              # Start up a KeyCloak instance for OAuth testing
              docker run -d --name keycloak \
                -e KC_HEALTH_ENABLED=true \
                -v "$(Pipeline.Workspace)/working/pipelines/keycloak-realm.json:/opt/keycloak/data/import/realm.json:ro" \
                -p 8080:8080 \
                --health-cmd="bash -c \"{ printf 'HEAD /health/ready HTTP/1.0\r\n\r\n' >&0; grep 'HTTP/1.0 200'; } 0<>/dev/tcp/localhost/9000\"" \
                --health-interval=5s \
                --health-timeout=5s \
                --health-retries=3 \
                --health-start-period=10s \
                quay.io/keycloak/keycloak:26.7 start-dev --import-realm

              # Start UI
              docker run -d --name ui \
                --network host \
                -v $(Pipeline.Workspace)/working/pipelines/ui-config.yaml:/etc/assemblyline/config.yml \
                -v $(Pipeline.Workspace)/working/pipelines/classification.yaml:/etc/assemblyline/classification.yml \
                --restart on-failure \
                --health-cmd="bash -c \"python -c 'import requests; requests.head(\"http://localhost:5000/healthz/live\", timeout=2).raise_for_status()' || exit 1\"" \
                --health-interval=30s \
                --health-timeout=30s \
                --health-retries=3 \
                --health-start-period=10s \
                --add-host=localhost:host-gateway \
                cccstemp.azurecr.io/assemblyline-ui:$TAG &
              
              # Start MCP
              docker run -d --name mcp --network host --restart on-failure $IMAGE:$TAG &

              # Start Ingress for routing
              docker run -d --name nginx \
                --network host \
                --restart on-failure \
                -e "UI_HOST=127.0.0.1" \
                -e "MCP_HOST=127.0.0.1" \
                -e "ACCESS_LOG=/dev/stdout" \
                -e "ERROR_LEVEL=info" \
                cccs/nginx-ssl-frontend:dev &
              wait

              # Run MCP tests
              docker run --name test \
                --network host \
                -v $(Pipeline.Workspace)/working/pipelines/ui-config.yaml:/etc/assemblyline/config.yml:ro \
                -v `pwd`:/test:ro \
                -w /test \
                cccstemp.azurecr.io/assemblyline-ui:$TAG \
                /bin/bash -c "pip install .[test] --only-deps; CI=1 pytest -rsx --durations=10"

              # Push images to registry if tests pass
              docker push $IMAGE -q --all-tags

            workingDirectory: $(Pipeline.Workspace)/working/assemblyline-mcp
            displayName: Test MCP
          - script: docker logs ui
            condition: failed()
            displayName: UI Logs
          - script: docker logs mcp
            condition: failed()
            displayName: MCP Logs
          - script: docker logs nginx
            condition: failed()
            displayName: NGINX Logs
