stages:
  - stage: build_frontend
    displayName: Build & Test Frontend
    dependsOn: build_python
    jobs:
      - job: frontend_ci
        displayName: Frontend CI (Typecheck, Lint, Test)
        timeoutInMinutes: 10
        pool:
          vmImage: ubuntu-latest

        steps:
          - checkout: none
          - download: current
            artifact: working

          - task: NodeTool@0
            displayName: 'Use Node 22.x'
            inputs:
              versionSpec: 22.x

          # --- Ensure cache directories exist ---
          - script: |
              mkdir -p /home/vsts/.pnpm-store
              mkdir -p $(Pipeline.Workspace)/working/assemblyline-ui-frontend/node_modules
            displayName: Ensure cache directories exist

          # --- Cache PNPM store and node_modules ---
          - task: Cache@2
            inputs:
              key: 'pnpm | "$(Agent.OS)" | $(Pipeline.Workspace)/working/assemblyline-ui-frontend/pnpm-lock.yaml'
              restoreKeys: |
                pnpm | "$(Agent.OS)"
              path: |
                /home/vsts/.pnpm-store
                $(Pipeline.Workspace)/working/assemblyline-ui-frontend/node_modules
            displayName: Cache PNPM dependencies

          # --- Install dependencies ---
          - script: |
              npm install -g pnpm@10.8.1 concurrently
              pnpm config set store-dir /home/vsts/.pnpm-store
              pnpm install --frozen-lockfile
            workingDirectory: $(Pipeline.Workspace)/working/assemblyline-ui-frontend
            displayName: Install dependencies

          # --- Run TypeScript, Lint, and Tests concurrently ---
          - script: |
              echo "--- Running TypeScript, ESLint, and Tests concurrently ---"
              pnpm concurrently \
                -n "typecheck,lint,test" \
                -c "blue,green,magenta" \
                "pnpm run typecheck" \
                "pnpm run lint:ci" \
                "pnpm run test:ci"
            workingDirectory: $(Pipeline.Workspace)/working/assemblyline-ui-frontend
            displayName: Run CI Checks (Typecheck + Lint + Tests)

      # --- Build job ---
      - job: build_frontend
        dependsOn: frontend_ci
        displayName: Build Frontend Docker Image
        pool:
          vmImage: ubuntu-latest

        steps:
          - checkout: none
          - download: current
            artifact: working

          - task: NodeTool@0
            displayName: 'Use Node 22.x'
            inputs:
              versionSpec: 22.x

          # --- Restore PNPM cache ---
          - task: Cache@2
            inputs:
              key: 'pnpm | "$(Agent.OS)" | $(Pipeline.Workspace)/working/assemblyline-ui-frontend/pnpm-lock.yaml'
              path: /home/vsts/.pnpm-store
            displayName: Restore PNPM Cache (Build)

          # --- Build Frontend ---
          - script: |
              npm install -g pnpm@10.8.1
              pnpm config set store-dir /home/vsts/.pnpm-store
              pnpm install --frozen-lockfile
              pnpm run build
            workingDirectory: $(Pipeline.Workspace)/working/assemblyline-ui-frontend
            displayName: Build Frontend Assets

          # --- Build & Push Docker Image ---
          - task: Docker@2
            displayName: Login to docker registry
            inputs:
              command: login
              containerRegistry: cccstemp

          - script: |
              set -exv
              if [[ "$TAG" == *stable* ]]; then BUILD_TYPE=stable; else BUILD_TYPE=latest; fi
              VERSION=${TAG/stable}
              VERSION=${VERSION/beta/b}
              SERIES="$(expr $TAG : '\([0-9]\+\.[0-9]\+\.\)' )${BUILD_TYPE}"
              IMAGE=cccstemp.azurecr.io/assemblyline-ui-frontend

              docker build \
                --build-arg version=$VERSION \
                -t $IMAGE:$TAG \
                -t $IMAGE:$BUILD_TYPE \
                -t $IMAGE:$SERIES \
                .
              docker push $IMAGE --all-tags
            workingDirectory: $(Pipeline.Workspace)/working/assemblyline-ui-frontend
            displayName: Build & Push Docker Image
