stages:
  - stage: rust_source_setup
    displayName: Get Rust Source
    dependsOn: []
    jobs:
      # Check out source and add tag
      - job: rust_source_setup
        displayName: Get Rust Source
        steps:
          - checkout: RustRepo
            path: assemblyline-rust
            persistCredentials: true
          - script: |
              set -e
              # Figure out what the build kind is
              export TAG=${BUILD_SOURCEBRANCH#"refs/tags/"}
              export VERSION=${BUILD_SOURCEBRANCH#"refs/tags/v"}
              if [[ "$VERSION" == *stable* ]];
              then
                export BRANCH=main;
              elif [[ "$VERSION" == *dev* ]];
              then
                export BRANCH=dev;
              else
                exit 1;
              fi

              echo "Building $VERSION On branch $BRANCH"
              export VERSION=${VERSION/stable}
              export VERSION=${VERSION/beta/b}

              git fetch origin ${BRANCH}
              git checkout ${BRANCH}
              git tag ${TAG}
              git push origin ${TAG}

            workingDirectory: $(Pipeline.Workspace)/assemblyline-rust
            displayName: Tag Source
          - publish: $(Pipeline.Workspace)/assemblyline-rust
            artifact: assemblyline-rust
  - stage: test_rust
    displayName: Test Rust Components
    dependsOn: rust_source_setup
    jobs:
      - job: test_filestore
        dependsOn: []
        displayName: Test Filestore
        steps:
          - checkout: none
          - download: current
            artifact: assemblyline-rust
          - task: Docker@2
            displayName: Login to docker registry
            inputs:
              command: login
              containerRegistry: cccstemp
          - script: |
              set -e
              docker pull cccstemp.azurecr.io/assemblyline-rust-builder:latest
              (cd assemblyline-filestore; docker compose up -d --wait)
              docker run -v ${PWD}:/usr/src/ \
                        --network=host \
                        cccstemp.azurecr.io/assemblyline-rust-builder:latest \
                        bash -c 'cd assemblyline-filestore; cargo test --target-dir /out'
            workingDirectory: $(Pipeline.Workspace)/assemblyline-rust
            displayName: Test Filestore
      - job: test_markings
        dependsOn: []
        displayName: Test Markings
        steps:
          - checkout: none
          - download: current
            artifact: assemblyline-rust
          - task: Docker@2
            displayName: Login to docker registry
            inputs:
              command: login
              containerRegistry: cccstemp
          - script: |
              set -e
              docker pull cccstemp.azurecr.io/assemblyline-rust-builder:latest
              docker run -v ${PWD}:/usr/src/ \
                        --network=host \
                        cccstemp.azurecr.io/assemblyline-rust-builder:latest \
                        bash -c 'cd assemblyline-markings; cargo test --target-dir /out'
            workingDirectory: $(Pipeline.Workspace)/assemblyline-rust
            displayName: Test Markings
      - job: test_server
        dependsOn: []
        displayName: Test Server
        steps:
          - checkout: none
          - download: current
            artifact: assemblyline-rust
          - task: Docker@2
            displayName: Login to docker registry
            inputs:
              command: login
              containerRegistry: cccstemp
          - script: |
              set -e
              docker pull cccstemp.azurecr.io/assemblyline-rust-builder:latest
              (cd assemblyline-server; docker compose up -d --wait)
              docker run -v ${PWD}:/usr/src/ \
                        --network=host \
                        cccstemp.azurecr.io/assemblyline-rust-builder:latest \
                        bash -c 'cd assemblyline-server; cargo test --target-dir /out'
            workingDirectory: $(Pipeline.Workspace)/assemblyline-rust
            displayName: Test Server
      - job: test_environment_template
        dependsOn: []
        displayName: Test Environment Template
        steps:
          - checkout: none
          - download: current
            artifact: assemblyline-rust
          - task: Docker@2
            displayName: Login to docker registry
            inputs:
              command: login
              containerRegistry: cccstemp
          - script: |
              set -e
              docker pull cccstemp.azurecr.io/assemblyline-rust-builder:latest
              docker run -v ${PWD}:/usr/src/ \
                        --network=host \
                        cccstemp.azurecr.io/assemblyline-rust-builder:latest \
                        bash -c 'cd environment_template; cargo test --target-dir /out'
            workingDirectory: $(Pipeline.Workspace)/assemblyline-rust
            displayName: Test Environment Template
      - job: test_redis_objects
        dependsOn: []
        displayName: Test Redis Objects
        steps:
          - checkout: none
          - download: current
            artifact: assemblyline-rust
          - task: Docker@2
            displayName: Login to docker registry
            inputs:
              command: login
              containerRegistry: cccstemp
          - script: |
              set -e
              docker pull cccstemp.azurecr.io/assemblyline-rust-builder:latest
              (cd redis-objects; docker compose up -d --wait)
              docker run -v ${PWD}:/usr/src/ \
                        --network=host \
                        cccstemp.azurecr.io/assemblyline-rust-builder:latest \
                        bash -c 'cd redis-objects; cargo test --target-dir /out'
            workingDirectory: $(Pipeline.Workspace)/assemblyline-rust
            displayName: Test Redis Objects

