
name: build

trigger:
  tags:
    include: ["v*"]
pr: none

pool:
  vmImage: "ubuntu-20.04"

resources:
  containers:
    - container: redis
      image: redis
      ports:
        - 6379:6379
    - container: sftp
      image: linuxserver/openssh-server
      env:
        SUDO_ACCESS: "false"
        PASSWORD_ACCESS: "true"
        USER_PASSWORD: "password"
        USER_NAME: "user"
        LOG_STDOUT: "true"
      ports:
        - 2222:2222
    - container: es7
      image: cccs/elasticsearch:7.17.4
      env:
        ES_JAVA_OPTS: "-Xms256m -Xmx512m"
        DISCOVERY_TYPE: "single-node"
        ELASTIC_PASSWORD: "devpass"
      ports:
        - 9200:9200
    - container: es8
      image: cccs/elasticsearch:8.10.2
      env:
        ES_JAVA_OPTS: "-Xms256m -Xmx512m"
        DISCOVERY_TYPE: "single-node"
        ELASTIC_PASSWORD: "devpass"
      ports:
        - 9200:9200
    - container: minio
      image: cccs/minio
      env:
        MINIO_ACCESS_KEY: al_storage_key
        MINIO_SECRET_KEY: Ch@ngeTh!sPa33w0rd
      ports:
        - 9000:9000
  repositories:
  - repository: BuildRepo
    type: github
    endpoint: github-repo-sa
    name: CybercentreCanada/assemblyline
    ref: '$(Build.SourceBranch)'
  - repository: DocsRepo
    type: github
    endpoint: github-repo-sa
    name: CybercentreCanada/assemblyline4_docs

stages:
  # Build Python packages
  - template: templates/stages/build-python.yaml

  # Build/Test Frontend
  - template: templates/stages/build-test-frontend.yaml

  # Build Base
  - template: templates/stages/build-base.yaml

  # Build Core
  - template: templates/stages/build-container.yaml
    parameters:
      baseImage: assemblyline
      component: assemblyline-core
      dependsOn: ["build_base"]
      dockerFile: deployment/Dockerfile

  # Service Server
  - template: templates/stages/build-container.yaml
    parameters:
      baseImage: assemblyline-core
      component: assemblyline-service-server
      dependsOn: ["build_core"]
      dockerFile: docker/Dockerfile

  # Service Base
  - template: templates/stages/build-container.yaml
    parameters:
      baseImage: assemblyline
      component: assemblyline-v4-service
      dependsOn: ["build_base"]
      dockerFile: docker/Dockerfile
      imageName: assemblyline-v4-service-base


  # ResultSample Service
  - template: templates/stages/build-container.yaml
    parameters:
      baseImage: assemblyline-v4-service-base
      component: assemblyline-v4-service
      dependsOn: ["build_v4_service_base"]
      dockerFile: assemblyline_result_sample_service/Dockerfile
      imageName: assemblyline-service-resultsample

  # UI (API)
  - template: templates/stages/build-container.yaml
    parameters:
      baseImage: assemblyline
      component: assemblyline-ui
      dependsOn: ["build_base", "build_python"]
      dockerFile: docker/ui/Dockerfile
      imageName: assemblyline-ui

  # SocketIO
  - template: templates/stages/build-container.yaml
    parameters:
      baseImage: assemblyline
      component: assemblyline-ui
      dependsOn: ["build_base", "build_python"]
      dockerFile: docker/socketio/Dockerfile
      imageName: assemblyline-socketio

  # External Lookup: Assemblyline
  - template: templates/stages/build-container.yaml
    parameters:
      baseImage: assemblyline
      component: assemblyline-ui
      dependsOn: ["build_base", "build_python"]
      imageName: assemblyline-ui-plugin-lookup-assemblyline
      buildContext: ./assemblyline_lookup/.
      workingDirectory: $(Pipeline.Workspace)/working/assemblyline-ui/plugins/external_lookup

  # External Lookup: MalwareBazaar
  - template: templates/stages/build-container.yaml
    parameters:
      baseImage: assemblyline
      component: assemblyline-ui
      dependsOn: ["build_base", "build_python"]
      imageName: assemblyline-ui-plugin-lookup-malwarebazaar
      buildContext: ./malware_bazaar/.
      workingDirectory: $(Pipeline.Workspace)/working/assemblyline-ui/plugins/external_lookup

  # External Lookup: VirusTotal
  - template: templates/stages/build-container.yaml
    parameters:
      baseImage: assemblyline
      component: assemblyline-ui
      dependsOn: ["build_base", "build_python"]
      imageName: assemblyline-ui-plugin-lookup-virustotal
      buildContext: ./virustotal/.
      workingDirectory: $(Pipeline.Workspace)/working/assemblyline-ui/plugins/external_lookup

  - stage: test
    dependsOn: [build_base, build_core, build_ui, build_frontend, build_service_server, build_v4_service_base]
    displayName: Test Containers
    jobs:
      - job: test_base
        displayName: Test Base Image
        timeoutInMinutes: 10
        strategy:
          matrix:
            elasticsearch_7:
              elasticsearch: es7
            elasticsearch_8:
              elasticsearch: es8
        services:
          elasticsearch: $[ variables['elasticsearch'] ]
          sftp: sftp
          redis: redis
          minio: minio
        steps:
          - checkout: none
          - download: current
            artifact: working
          - task: Docker@2
            displayName: Login to docker registry
            inputs:
              command: login
              containerRegistry: cccstemp
          - script: |
              set -exv  # Echo commands before they are run
              export TAG=${BUILD_SOURCEBRANCH#"refs/tags/v"}

              cd assemblyline-base

              docker run -v `pwd`/test:/test \
                         -v $(Pipeline.Workspace)/working/pipelines/base-config.yaml:/etc/assemblyline/config.yml \
                         -w /test \
                         --network host \
                         cccstemp.azurecr.io/assemblyline:${TAG} \
                         /bin/bash -c "pip install -r requirements.txt; CI=1 pytest -rsx --durations=10"
            workingDirectory: $(Pipeline.Workspace)/working
            displayName: Test Base

      - job: test_core
        timeoutInMinutes: 10
        services:
          elasticsearch: es8
          redis: redis
        displayName: Test Core Image
        steps:
          - checkout: none
          - download: current
            artifact: working
          - task: Docker@2
            displayName: Login to docker registry
            inputs:
              command: login
              containerRegistry: cccstemp
          - script: |
              set -exv  # Echo commands before they are run
              export TAG=${BUILD_SOURCEBRANCH#"refs/tags/v"}

              cd assemblyline-core

              docker run -v `pwd`/test:/test \
                         -v $(Pipeline.Workspace)/working/pipelines/base-config.yaml:/etc/assemblyline/config.yml \
                         -w /test \
                         --network host \
                         cccstemp.azurecr.io/assemblyline-core:${TAG} /bin/bash -c "pip install -r requirements.txt; CI=1 pytest -rsx --durations=10"
            workingDirectory: $(Pipeline.Workspace)/working
            displayName: Test Core

      - job: test_ui
        timeoutInMinutes: 10
        services:
          elasticsearch: es8
          redis: redis
          minio: minio
        displayName: Test UI Image
        steps:
          - checkout: none
          - download: current
            artifact: working
          - task: Docker@2
            displayName: Login to docker registry
            inputs:
              command: login
              containerRegistry: cccstemp
          - script: |
              set -e
              export TAG=${BUILD_SOURCEBRANCH#"refs/tags/v"}

              docker run -d --name ui --network host -v $(Pipeline.Workspace)/working/pipelines/ui-config.yaml:/etc/assemblyline/config.yml -v $(Pipeline.Workspace)/working/pipelines/classification.yaml:/etc/assemblyline/classification.yml --restart on-failure cccstemp.azurecr.io/assemblyline-ui:$TAG &
              docker run -d --name socketsrv --network host -v $(Pipeline.Workspace)/working/pipelines/ui-config.yaml:/etc/assemblyline/config.yml -v $(Pipeline.Workspace)/working/pipelines/classification.yaml:/etc/assemblyline/classification.yml --restart on-failure cccstemp.azurecr.io/assemblyline-socketio:$TAG &
              docker run -d --name frontend --network host --restart on-failure cccstemp.azurecr.io/assemblyline-ui-frontend:$TAG &
              docker run -d --name nginx --network host --restart on-failure -e "FRONTEND_HOST=127.0.0.1" -e "UI_HOST=127.0.0.1" -e "SOCKET_HOST=127.0.0.1" -e "TEMPLATE=minimal" -e "FQDN=localhost" -e "ACCESS_LOG=/dev/stdout" -e "ERROR_LEVEL=info" cccs/nginx-ssl-frontend &
              wait

              wget http://localhost:5000/healthz/ready --timeout=2 --retry-on-http-error=502 --retry-on-http-error=503 --waitretry=10 --retry-connrefused
              wget http://localhost:5002/healthz/ready --timeout=2 --retry-on-http-error=502 --retry-on-http-error=503 --waitretry=10 --retry-connrefused
              wget https://localhost --no-check-certificate --timeout=2 --retry-on-http-error=502 --waitretry=10 --retry-connrefused

              docker run -v `pwd`/test:/test \
                         -v $(Pipeline.Workspace)/working/pipelines/ui-config.yaml:/etc/assemblyline/config.yml \
                         -v $(Pipeline.Workspace)/working/pipelines/classification.yaml:/etc/assemblyline/classification.yml \
                         -w /test \
                         --network host \
                         cccstemp.azurecr.io/assemblyline-socketio:${TAG} \
                         /bin/bash -c "pip install -r requirements.txt; CI=1 pytest -rsx --durations=10"
            workingDirectory: $(Pipeline.Workspace)/working/assemblyline-ui
            displayName: Test UI
          - script: docker logs ui
            condition: failed()
            displayName: UI Logs
          - script: docker logs socketsrv
            condition: failed()
            displayName: SocketIO Logs
          - script: docker logs frontend
            condition: failed()
            displayName: Frontend Logs
          - script: docker logs nginx
            condition: failed()
            displayName: NGINX Logs

      - job: test_service_server
        timeoutInMinutes: 10
        services:
          elasticsearch: es8
          redis: redis
          minio: minio
        displayName: Test Service Server Image
        steps:
          - checkout: none
          - download: current
            artifact: working
          - task: Docker@2
            displayName: Login to docker registry
            inputs:
              command: login
              containerRegistry: cccstemp
          - script: |
              set -e
              export TAG=${BUILD_SOURCEBRANCH#"refs/tags/v"}

              docker run -d --name server --network host --restart on-failure cccstemp.azurecr.io/assemblyline-service-server:$TAG

              docker run -v `pwd`/test:/test \
                         -v $(Pipeline.Workspace)/working/pipelines/base-config.yaml:/etc/assemblyline/config.yml \
                         -w /test \
                         --network host \
                         cccstemp.azurecr.io/assemblyline-service-server:${TAG} \
                         /bin/bash -c "pip install -r requirements.txt; CI=1 pytest -rsx --durations=10"
            workingDirectory: $(Pipeline.Workspace)/working/assemblyline-service-server
            displayName: Test Service Server

      - job: test_service_base
        timeoutInMinutes: 10
        services:
          elasticsearch: es8
          redis: redis
          minio: minio
        displayName: Test Service Base Image
        steps:
          - checkout: none
          - download: current
            artifact: working
          - task: Docker@2
            displayName: Login to docker registry
            inputs:
              command: login
              containerRegistry: cccstemp
          - script: |
              set -e
              export TAG=${BUILD_SOURCEBRANCH#"refs/tags/v"}

              docker run -v `pwd`/test:/test \
                         -v $(Pipeline.Workspace)/working/pipelines/base-config.yaml:/etc/assemblyline/config.yml \
                         -w /test \
                         --network host \
                         cccstemp.azurecr.io/assemblyline-v4-service-base:${TAG} \
                         /bin/bash -c "pip install -r requirements.txt; CI=1 pytest -rsx --durations=10"
            workingDirectory: $(Pipeline.Workspace)/working/assemblyline-v4-service
            displayName: Test Service Base

  - stage: deploy
    displayName: Deploy
    jobs:
    - job: deploy_python
      displayName: Deploy Python Packages
      dependsOn: []
      variables:
        - group: deployment-information
      steps:
        - checkout: none
        - download: current
          artifact: working
        - script: |
            set -exv  # Echo commands before they are run
            sudo env "PATH=$PATH" python -m pip install --no-cache-dir -U 'urllib3<2' twine
            ls dist
            twine upload --skip-existing dist/*
          workingDirectory: $(Pipeline.Workspace)/working/
          displayName: Deploy to PyPI
          retryCountOnTaskFailure: 3
          env:
            TWINE_USERNAME: $(twineUsername)
            TWINE_PASSWORD: $(twinePassword)
    - job: deploy_containers
      displayName: Deploy Docker Image
      dependsOn: []
      strategy:
        matrix:
          Base:
            CONTAINER_NAME: assemblyline
          Core:
            CONTAINER_NAME: assemblyline-core
          UI:
            CONTAINER_NAME: assemblyline-ui
          UI-plugin-lookup-assemblyline:
            CONTAINER_NAME: assemblyline-ui-plugin-lookup-assemblyline
          UI-plugin-lookup-malwarebazaar:
            CONTAINER_NAME: assemblyline-ui-plugin-lookup-malwarebazaar
          UI-plugin-lookup-virustotal:
            CONTAINER_NAME: assemblyline-ui-plugin-lookup-virustotal
          UI-frontend:
            CONTAINER_NAME: assemblyline-ui-frontend
          SocketIO:
            CONTAINER_NAME: assemblyline-socketio
          Service-Server:
            CONTAINER_NAME: assemblyline-service-server
          Service-Base:
            CONTAINER_NAME: assemblyline-v4-service-base
          Sample-Service:
            CONTAINER_NAME: assemblyline-service-resultsample
      steps:
        - checkout: none
        - task: Docker@2
          displayName: Login to docker hub
          inputs:
            command: login
            containerRegistry: dockerhub
        - task: Docker@2
          displayName: Login to github packages
          inputs:
            command: login
            containerRegistry: github-packages-sa
        - task: Docker@2
          displayName: Login to temp registry
          inputs:
            command: login
            containerRegistry: cccstemp
        - task: Docker@2
          displayName: Login to chimera
          inputs:
            command: login
            containerRegistry: CHIMERA-U-ACR2
        - script: |
            set -exv  # Echo commands before they are run
            export TAG=${BUILD_SOURCEBRANCH#"refs/tags/v"}
            if [[ "$TAG" == *stable* ]]; then export BUILD_TYPE=stable; else export BUILD_TYPE=latest; fi
            export VERSION=${TAG/stable}
            export VERSION=${VERSION/beta/b}
            export SERIES="`expr $TAG : '\([0-9]\+\.[0-9]\+\.\)'`${BUILD_TYPE}"

            export BUILT_AS=cccstemp.azurecr.io/${CONTAINER_NAME}:$TAG
            docker pull $BUILT_AS

            for IMAGE in "cccs/" "docker.pkg.github.com/cybercentrecanada/assemblyline/" "uchimera.azurecr.io/cccs/"
            do
              docker tag $BUILT_AS ${IMAGE}${CONTAINER_NAME}:$TAG
              docker tag $BUILT_AS ${IMAGE}${CONTAINER_NAME}:$BUILD_TYPE
              docker tag $BUILT_AS ${IMAGE}${CONTAINER_NAME}:$SERIES
              docker push ${IMAGE}${CONTAINER_NAME} --all-tags
            done
          displayName: Deploy base Docker Hub
          retryCountOnTaskFailure: 3
    - job: update_odm_docs
      displayName: "Update Assemblyline4 Documentation"
      steps:
        - download: current
          artifact: working
        - checkout: DocsRepo
          path: assemblyline4_docs
          persistCredentials: true
        - task: Docker@2
          displayName: Login to temp registry
          inputs:
            command: login
            containerRegistry: cccstemp
        - script: |
            set -exv  # Echo commands before they are run
            export TAG=${BUILD_SOURCEBRANCH#"refs/tags/v"}

            # Prepare output directory
            cp -rf $(Agent.BuildDirectory)/assemblyline4_docs .
            (cd assemblyline4_docs && git checkout master)
            chmod -R a+rw ./assemblyline4_docs

            # Generate documentation from script
            docker run -v $PWD/assemblyline4_docs:/tmp/assemblyline4_docs:rw \
                       -v $PWD/assemblyline-base:/tmp/assemblyline-base:ro \
                       -v $PWD/gen_docs.py:/tmp/gen_docs.py:ro \
                       -w /tmp \
                       cccstemp.azurecr.io/assemblyline:${TAG} \
                       /bin/bash -c 'pip install mkdocs-material==7.3.6 mkdocs-static-i18n && python gen_docs.py . "/assemblyline4_docs"'
            if [[ "$TAG" == *stable* ]]
            then
              # Commit documentation changes (if any) to Documentation repo
              cd assemblyline4_docs
              if [[ `git status --porcelain` ]]; then
                git add .
                git config --global user.email "assemblyline@cyber.gc.ca"
                git config --global user.name "Azure Pipeline"
                git commit -m "Pipeline: Release $TAG documentation"
                git push
              fi
            fi

          workingDirectory: $(Pipeline.Workspace)/working/
          displayName: "Run script to generate documentation and commit changes"
          retryCountOnTaskFailure: 3
