
name: test
trigger:
  branches:
    exclude:
      - "main"

pool:
  vmImage: "ubuntu-latest"

variables:
  TAG: 4.7.0.stable0
  VERSION:  4.7.0.stable0
  BUILD_KIND: stable
  SERIES: 4.7.stable

resources:
  containers:
    - container: redis
      image: redis
      ports:
        - 6379:6379
    - container: sftp
      image: linuxserver/openssh-server
      env:
        SUDO_ACCESS: "false"
        PASSWORD_ACCESS: "true"
        USER_PASSWORD: "password"
        USER_NAME: "user"
        LOG_STDOUT: "true"
      ports:
        - 2222:2222
    - container: elasticsearch
      image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
      env:
        xpack.security.enabled: true
        discovery.type: single-node
        ES_JAVA_OPTS: "-Xms256m -Xmx512m"
        ELASTIC_PASSWORD: devpass
      ports:
        - 9200:9200
    - container: minio
      image: cccs/minio
      env:
        MINIO_ACCESS_KEY: al_storage_key
        MINIO_SECRET_KEY: Ch@ngeTh!sPa33w0rd
      ports:
        - 9000:9000
    - container: openldap
      image: docker.io/bitnamilegacy/openldap:2.6
      env:
        LDAP_PORT_NUMBER: 389
        LDAP_ROOT: dc=assemblyline,dc=local
        LDAP_ADMIN_PASSWORD: admin
        LDAP_USERS: ldap_user
        LDAP_PASSWORDS: ldap_password
        LDAP_USER_OU: people
      ports:
        - 389:389
  repositories:
  - repository: BuildRepo
    type: github
    endpoint: github-repo-sa
    name: CybercentreCanada/assemblyline
    ref: '$(Build.SourceBranch)'
  - repository: RustRepo
    type: github
    endpoint: github-repo-sa
    name: CybercentreCanada/assemblyline-rust


stages:
  ### BUILDING ###
  # Build Python packages
  - template: templates/stages/build-python.yaml
    parameters:
      test_only: true

  # Build/Test Frontend
  - template: templates/stages/build-test-frontend.yaml

  # Build Base
  - template: templates/stages/build-base.yaml

  # Build Core
  - template: templates/stages/build-container.yaml
    parameters:
      baseImage: assemblyline
      component: assemblyline-core
      dependsOn: ["build_base"]
      dockerFile: deployment/Dockerfile

  # Service Server
  - template: templates/stages/build-container.yaml
    parameters:
      baseImage: assemblyline-core
      component: assemblyline-service-server
      dependsOn: ["build_core"]
      dockerFile: docker/Dockerfile

  # Service Base
  - template: templates/stages/build-container.yaml
    parameters:
      baseImage: assemblyline
      component: assemblyline-v4-service
      dependsOn: ["build_base"]
      dockerFile: docker/Dockerfile
      imageName: assemblyline-v4-service-base


  # ResultSample Service
  - template: templates/stages/build-container.yaml
    parameters:
      baseImage: assemblyline-v4-service-base
      component: assemblyline-v4-service
      dependsOn: ["build_v4_service_base"]
      dockerFile: assemblyline_result_sample_service/Dockerfile
      imageName: assemblyline-service-resultsample

  # UI (API)
  - template: templates/stages/build-container.yaml
    parameters:
      baseImage: assemblyline
      component: assemblyline-ui
      dependsOn: ["build_base"]
      dockerFile: docker/ui/Dockerfile
      imageName: assemblyline-ui

  # SocketIO
  - template: templates/stages/build-container.yaml
    parameters:
      baseImage: assemblyline
      component: assemblyline-ui
      dependsOn: ["build_base"]
      dockerFile: docker/socketio/Dockerfile
      imageName: assemblyline-socketio

  # External Lookup: Assemblyline
  - template: templates/stages/build-container.yaml
    parameters:
      baseImage: assemblyline
      component: assemblyline-ui
      dependsOn: ["build_base"]
      imageName: assemblyline-ui-plugin-lookup-assemblyline
      workingDirectory: $(Pipeline.Workspace)/working/assemblyline-ui/plugins/external_lookup/assemblyline_lookup

  # External Lookup: MalwareBazaar
  - template: templates/stages/build-container.yaml
    parameters:
      baseImage: assemblyline
      component: assemblyline-ui
      dependsOn: ["build_base"]
      imageName: assemblyline-ui-plugin-lookup-malwarebazaar
      workingDirectory: $(Pipeline.Workspace)/working/assemblyline-ui/plugins/external_lookup/malware_bazaar

  # External Lookup: VirusTotal
  - template: templates/stages/build-container.yaml
    parameters:
      baseImage: assemblyline
      component: assemblyline-ui
      dependsOn: ["build_base"]
      imageName: assemblyline-ui-plugin-lookup-virustotal
      workingDirectory: $(Pipeline.Workspace)/working/assemblyline-ui/plugins/external_lookup/virustotal

  # The rust server code tests and builds at the same time, both must pass before deployment
  - template: templates/stages/test-rust.yaml
  - template: templates/stages/build-rust.yaml

  ### TESTING ###
  - template: templates/stages/test-container.yaml
    parameters:
      imageName: assemblyline
      component: assemblyline-base
      dependsOn: [build_base]

  - template: templates/stages/test-container.yaml
    parameters:
      component: assemblyline-core
      dependsOn: [build_core]

  - template: templates/stages/test-ui.yaml

  - template: templates/stages/test-e2e.yaml

  - template: templates/stages/test-container.yaml
    parameters:
      component: assemblyline-service-server
      dependsOn: [build_service_server]
      additionalSteps:
        - script: |
            docker run -d --name server --network host --restart on-failure cccstemp.azurecr.io/assemblyline-service-server:$TAG

  - template: templates/stages/test-container.yaml
    parameters:
      imageName: assemblyline-v4-service-base
      component: assemblyline-v4-service
      dependsOn: [build_v4_service_base]
