name: Generate SBOM with Syft

on:
  push:
    branches:
      - sbom-workflow
  workflow_dispatch:

permissions:
  contents: write  

jobs:
  generate_sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Download Syft
        uses: anchore/sbom-action/download-syft@v0
        id: download-syft
        with:
          syft-version: "v1.19.0"
      
      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          path: .
          format: spdx-json
          artifact-name: sbom.spdx
          

      - name: Upload SBOM as artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-file
          path: sbom.spdx.json
